### ISSUE TITLE
Systemd check on Raspberry Pi fails

### ISSUE THREAD

**Issue by jonwitts** [virtualhere/script#7]
Hi there,

I have just tried using the server_install script on a Raspberry Pi and the systemd check fails.... 

I think it should be checking for the existence of /etc/systemd/system on the Pi not /run/systemd/system...

Jon

**Comment by msbroadf** [comment]
Yes actually that is correct,

**Comment by virtualhere** [comment]
Thanks, yes ive merged that pull request now.
