### ISSUE TITLE
Raspbian buster

### ISSUE THREAD

**Issue by blackfed** [virtualhere/script#9]
Hi, I have an issue on buster with the mayflash dolphin bar. When I use my MacBook as server it works without problems, when I use my pi3 as server, the moment when I launch a game in dolphin the wiimote gets disconnected. When you launch a game in dolphin the amount of data the wiimote sends is higher than the moment when you connect it to the emulator, so I think it could be something related to this.

**Comment by virtualhere** [comment]
Hi, actually this is not the place for virtualhere support unrelated to the script. Please post any questions here https://www.virtualhere.com/forum/1

Now regarding mayflash, try right clicking on the mayflash in the virtualhere client, select Custom Event Handler.. and paste in exactly this line:

onReset.$VENDOR_ID$.$PRODUCT_ID$=

then press OK. Then see if it works ok now via virtualhere.
